### ISSUE TITLE
How to training CommonLayout+SDFusion?

### ISSUE THREAD

**Issue by SceneLinker** [ymxlzgy/commonscenes#13]
Hello, thank you for sharing your awesome work!

Is there any method or command available for training 'CommonLayout+SDFusion'?

I would appreciate it if you could share it!

**Comment by ymxlzgy** [comment]
Hey, this baseline is separately trained. You can train SDFusion with textual information first and CommonLayout after. During inference, CommonLayout needs to be conducted first, and SDFusion generates shapes according to each textual information. Finally, the shapes can be populated to bboxes from CommonLayout.
