### ISSUE TITLE
relationships with walls

### ISSUE THREAD

**Issue by d-sharafeldeen** [ymxlzgy/commonscenes#2]
Hi,
Thanks for sharing your work.
I am just wondering why there are relationships between the objects and (the floor and ceiling) but not with walls.  As having the relationships with walls, we could know the room boundaries and dimensions.
Another question: could you explain how we could know the room shape, boundaries, and dimensions?

**Comment by ymxlzgy** [comment]
> Hi, Thanks for sharing your work. I am just wondering why there are relationships between the objects and (the floor and ceiling) but not with walls. As having the relationships with walls, we could know the room boundaries and dimensions. Another question: could you explain how we could know the room shape, boundaries, and dimensions?

Hi,
Good question! In this work, we only research how the relationship among objects affects each object's appearance, e.g., if they are semantically coherent and geometrically consistent, regardless of the boundaries (walls) and room shapes. You can see it as an "open-world/-boundary" generation problem. But what you mentioned could be a future direction. By the way, we didn't notice if the files processed by ATISS provided the information on the walls. If they really provide, you can use and modify the annotation scripts to get labels with walls easily.
Cheers!

**Comment by ymxlzgy** [comment]
Hi, I will close this issue for now. If you have further questions or other things to discuss, feel free to reopen this panel or start a new issue! Thanks!
