### ISSUE TITLE
Unable to synchronously open the file ori_sample_grid.h5

### ISSUE THREAD

**Issue by Aoihigashi** [ymxlzgy/commonscenes#3]
hi,
thanks for sharing this work! when I run eval_3dfront.py, I came across this error below, I have not run train_3dfront.py yet, I use  the trained model180 instead, I wonder if I have missed some files, I would appreciate if you could help me, thank you!

Have a good day!

(commonscenes) root@rtx6:/workspace/caitou/commonscenes/scripts# python eval_3dfront.py --exp /workspace/caitou/commonscenes/scripts/checkpoint/balancing/all --epoch 180 --visualize False --evaluate_diversity False --num_samples 5 --gen_shape False --no_stool True
2.0.1
100%|███████████████████████████████████████| 338M/338M [01:25<00:00, 4.14MiB/s]
loading CLIP
Checking for missing clip feats. This can be slow the first time.
  0%|                                                                                                                         | 0/370 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "eval_3dfront.py", line 800, in <module>
    evaluate()
  File "eval_3dfront.py", line 70, in evaluate
    test_dataset_rels_changes = ThreedFrontDatasetSceneGraph(
  File "/workspace/caitou/commonscenes/dataset/threedfront_dataset.py", line 183, in __init__
    self.__getitem__(index)
  File "/workspace/caitou/commonscenes/dataset/threedfront_dataset.py", line 379, in __getitem__
    bbox = normalize_box_params(bbox,file=self.box_normalized_stats)
  File "/workspace/caitou/commonscenes/helpers/util.py", line 530, in normalize_box_params
    stats = np.loadtxt(file)
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /workspace/caitou/commonscenes/FRONT/SG_FRONT/boxes_centered_stats_all_test.txt not found.
(commonscenes) root@rtx6:/workspace/caitou/commonscenes/scripts# python eval_3dfront.py --exp /workspace/caitou/commonscenes/scripts/checkpoint/balancing/all --epoch 180 --visualize False --evaluate_diversity False --num_samples 5 --gen_shape False --no_stool True
2.0.1
loading CLIP
Checking for missing clip feats. This can be slow the first time.
  0%|                                                                                                                         | 0/370 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "eval_3dfront.py", line 800, in <module>
    evaluate()
  File "eval_3dfront.py", line 70, in evaluate
    test_dataset_rels_changes = ThreedFrontDatasetSceneGraph(
  File "/workspace/caitou/commonscenes/dataset/threedfront_dataset.py", line 183, in __init__
    self.__getitem__(index)
  File "/workspace/caitou/commonscenes/dataset/threedfront_dataset.py", line 388, in __getitem__
    h5_f = h5py.File(sdf_path, 'r')
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/workspace/caitou/commonscenes/FRONT/SG_FRONT/3D-FUTURE-SDF/1791e0c9-15fc-4fa9-80df-e73332ed6ce0/ori_sample_grid.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by ymxlzgy** [comment]
Hi,
So I guess you solved the bbox file issue? If didn't, you can download it [here](https://www.campar.in.tum.de/public_datasets/2023_commonscenes_zhai/bbox.zip). Did you download the 3D-FUTURE-SDF [here](https://github.com/ymxlzgy/commonscenes#:~:text=Download%203D%2DFUTURE%2DSDF.%20This%20is%20processed%20by%20ourselves%20on%20the%203D%2DFUTURE%20meshes%20using%20tools%20in%20SDFusion.)? If so, can you locate that file and run `h5ls -r xxx.h5` to check if you can see some information or if it is corrupted? I downloaded it and saw the information:
```
>> h5ls -r /media/ymxlzgy/Data/3D-FUTURE-SDF/1791e0c9-15fc-4fa9-80df-e73332ed6ce0/ori_sample_grid.h5
/                        Group
/norm_params             Dataset {4}
/pc_sdf_original         Dataset {1, 3}
/pc_sdf_sample           Dataset {262144, 1}
/sdf_params              Dataset {6}
```
And I also tried to open it by:
```
Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> h5_f = h5py.File("/media/ymxlzgy/Data/3D-FUTURE-SDF/1791e0c9-15fc-4fa9-80df-e73332ed6ce0/ori_sample_grid.h5", 'r')
>>> h5_f
<HDF5 file "ori_sample_grid.h5" (mode r)>
>>> 
```
There is no weird thing on my side.

**Comment by Aoihigashi** [comment]
> Hi, So I guess you solved the bbox file issue? If didn't, you can download it [here](https://www.campar.in.tum.de/public_datasets/2023_commonscenes_zhai/bbox.zip). Did you download the 3D-FUTURE-SDF [here](https://github.com/ymxlzgy/commonscenes#:~:text=Download%203D%2DFUTURE%2DSDF.%20This%20is%20processed%20by%20ourselves%20on%20the%203D%2DFUTURE%20meshes%20using%20tools%20in%20SDFusion.)? If so, can you locate that file and run `h5ls -r xxx.h5` to check if you can see some information or if it is corrupted? I downloaded it and saw the information:
> 
> ```
> >> h5ls -r /media/ymxlzgy/Data/3D-FUTURE-SDF/1791e0c9-15fc-4fa9-80df-e73332ed6ce0/ori_sample_grid.h5
> /                        Group
> /norm_params             Dataset {4}
> /pc_sdf_original         Dataset {1, 3}
> /pc_sdf_sample           Dataset {262144, 1}
> /sdf_params              Dataset {6}
> ```
> 
> And I also tried to open it by:
> 
> ```
> Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
> [GCC 11.2.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import h5py
> >>> h5_f = h5py.File("/media/ymxlzgy/Data/3D-FUTURE-SDF/1791e0c9-15fc-4fa9-80df-e73332ed6ce0/ori_sample_grid.h5", 'r')
> >>> h5_f
> <HDF5 file "ori_sample_grid.h5" (mode r)>
> >>> 
> ```
> 
> There is no weird thing on my side.

Thank you so much for your response. I have downloaded all the files, I think I made a mistake in the file paths, leading to this error.After placing SG_FRONT and bbox in the correct location, I resolved this issue,  and I have successfully executed the eval_3dfront.py with visualize set to False. However, when running with visualize set to True, I encountered a new error as follows:
Generation Mode
Traceback (most recent call last):
  File "eval_3dfront.py", line 800, in <module>
    evaluate()
  File "eval_3dfront.py", line 200, in evaluate
    validate_constrains_loop(modelArgs, test_dataloader_no_changes, model, epoch=args.epoch, normalized_file=normalized_file, with_diversity=args.evaluate_diversity,
  File "eval_3dfront.py", line 574, in validate_constrains_loop
    render_v2_full(model.type_, data['scan_id'], dec_objs.detach().cpu().numpy(), boxes_pred_den, angles_pred, classes=classes, render_type='v2', classed_idx=dec_objs,
  File "/workspace/caitou/commonscenes/helpers/visualize_scene.py", line 401, in render_v2_full
    lamp_mesh_list, trimesh_meshes, raw_meshes = get_generated_models_v2(box_and_angle, shapes_pred, cats, classes, mesh_dir, render_boxes=render_boxes, colors=color_palette[cats], without_lamp=without_lamp)
  File "/workspace/caitou/commonscenes/helpers/util.py", line 300, in get_generated_models_v2
    mesh_gen = sdf_to_mesh(shapes,render_all=True)
  File "/workspace/caitou/commonscenes/model/diff_utils/util_3d.py", line 196, in sdf_to_mesh
    device=sdf.device
AttributeError: 'NoneType' object has no attribute 'device'

**Comment by ymxlzgy** [comment]
Hi, I couldn't reproduce your problem, but I think you did not make the shape branch work. You need to set `gen_shape` and `visualize` to be true, according to this [line](https://github.com/ymxlzgy/commonscenes#:~:text=%2D%2Dgen_shape%3A%20set%20True%20if%20you%20want%20to%20make%20diffusion%2Dbased%20shape%20branch%20work.). You can also cancel the comment [here](https://github.com/ymxlzgy/commonscenes/blob/1665ffb81a32d7337d9c0caad1262917b37c39e0/scripts/eval_3dfront.py#L177) to do protection. If you really did, could you provide me more hints?

**Comment by Aoihigashi** [comment]
> Hi, I couldn't reproduce your problem, but I think you did not make the shape branch work. You need to set `gen_shape` and `visualize` to be true, according to this [line](https://github.com/ymxlzgy/commonscenes#:~:text=%2D%2Dgen_shape%3A%20set%20True%20if%20you%20want%20to%20make%20diffusion%2Dbased%20shape%20branch%20work.). You can also cancel the comment [here](https://github.com/ymxlzgy/commonscenes/blob/1665ffb81a32d7337d9c0caad1262917b37c39e0/scripts/eval_3dfront.py#L177) to do protection. If you really did, could you provide me more hints?

Good morning, I'm very sorry to bother you again. Following your instructions, I set gen_shape to true and successfully ran DDIM sampling for several hours. However, it seems that there is a display issue during the generation mode. I am running it on a Linux server without a graphical user interface, so there is a problem with the display. Below is the error I encountered. Thank you very much for your patience and time.

Running DDIM Sampling with 100 timesteps
DDIM Sampler: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:27<00:00,  3.67it/s]
Debug: mesh_gen: <pytorch3d.structures.meshes.Meshes object at 0x7f27f0c7b2b0>
Traceback (most recent call last):
  File "eval_3dfront.py", line 800, in <module>
    evaluate()
  File "eval_3dfront.py", line 200, in evaluate
    validate_constrains_loop(modelArgs, test_dataloader_no_changes, model, epoch=args.epoch, normalized_file=normalized_file, with_diversity=args.evaluate_diversity,
  File "eval_3dfront.py", line 574, in validate_constrains_loop
    render_v2_full(model.type_, data['scan_id'], dec_objs.detach().cpu().numpy(), boxes_pred_den, angles_pred, classes=classes, render_type='v2', classed_idx=dec_objs,
  File "/workspace/caitou/commonscenes/helpers/visualize_scene.py", line 456, in render_v2_full
    color_img = render_img(trimesh_meshes)
  File "/workspace/caitou/commonscenes/helpers/visualize_scene.py", line 87, in render_img
    renderer = pyrender.OffscreenRenderer(viewport_width=256, viewport_height=256)
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyrender/platforms/pyglet_platform.py", line 50, in init_context
    self._window = pyglet.window.Window(config=conf, visible=False,
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 138, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyglet/window/__init__.py", line 513, in __init__
    display = pyglet.canvas.get_display()
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyglet/canvas/__init__.py", line 59, in get_display
    return Display()
  File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyglet/canvas/xlib.py", line 88, in __init__
    raise NoSuchDisplayException(f'Cannot connect to "{name}"')
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

**Comment by Aoihigashi** [comment]
> > Hi, I couldn't reproduce your problem, but I think you did not make the shape branch work. You need to set `gen_shape` and `visualize` to be true, according to this [line](https://github.com/ymxlzgy/commonscenes#:~:text=%2D%2Dgen_shape%3A%20set%20True%20if%20you%20want%20to%20make%20diffusion%2Dbased%20shape%20branch%20work.). You can also cancel the comment [here](https://github.com/ymxlzgy/commonscenes/blob/1665ffb81a32d7337d9c0caad1262917b37c39e0/scripts/eval_3dfront.py#L177) to do protection. If you really did, could you provide me more hints?
> 
> Good morning, I'm very sorry to bother you again. Following your instructions, I set gen_shape to true and successfully ran DDIM sampling for several hours. However, it seems that there is a display issue during the generation mode. I am running it on a Linux server without a graphical user interface, so there is a problem with the display. Below is the error I encountered. Thank you very much for your patience and time.
> 
> Running DDIM Sampling with 100 timesteps DDIM Sampler: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:27<00:00, 3.67it/s] Debug: mesh_gen: <pytorch3d.structures.meshes.Meshes object at 0x7f27f0c7b2b0> Traceback (most recent call last): File "eval_3dfront.py", line 800, in evaluate() File "eval_3dfront.py", line 200, in evaluate validate_constrains_loop(modelArgs, test_dataloader_no_changes, model, epoch=args.epoch, normalized_file=normalized_file, with_diversity=args.evaluate_diversity, File "eval_3dfront.py", line 574, in validate_constrains_loop render_v2_full(model.type_, data['scan_id'], dec_objs.detach().cpu().numpy(), boxes_pred_den, angles_pred, classes=classes, render_type='v2', classed_idx=dec_objs, File "/workspace/caitou/commonscenes/helpers/visualize_scene.py", line 456, in render_v2_full color_img = render_img(trimesh_meshes) File "/workspace/caitou/commonscenes/helpers/visualize_scene.py", line 87, in render_img renderer = pyrender.OffscreenRenderer(viewport_width=256, viewport_height=256) File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in **init** self._create() File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create self._platform.init_context() File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyrender/platforms/pyglet_platform.py", line 50, in init_context self._window = pyglet.window.Window(config=conf, visible=False, File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyglet/window/xlib/**init**.py", line 138, in **init** super(XlibWindow, self).**init**(*args, **kwargs) File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyglet/window/**init**.py", line 513, in **init** display = pyglet.canvas.get_display() File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyglet/canvas/**init**.py", line 59, in get_display return Display() File "/workspace/conda/envs/commonscenes/lib/python3.8/site-packages/pyglet/canvas/xlib.py", line 88, in **init** raise NoSuchDisplayException(f'Cannot connect to "{name}"') pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

This is the command I executed：python eval_3dfront.py --exp /workspace/caitou/commonscenes/scripts/checkpoint/balancing/all --epoch 180 --visualize True --evaluate_diversity False --num_samples 5 --gen_shape True --no_stool True

**Comment by ymxlzgy** [comment]
Hi,
Thanks for trying and bearing with me. I never tried to run on a headless server actually, so maybe some rendering code wouldn't work properly and need some adjustments. The problematic line I saw you were trying is top-down image rendering. If you don't really need it, just need to turn `store_img` as `False` [here](https://github.com/ymxlzgy/commonscenes/blob/1665ffb81a32d7337d9c0caad1262917b37c39e0/scripts/eval_3dfront.py#L575 ), or you need to adjust pyrender settings for the headless rendering. From what I googled, you can try to use `xvfb-run` by `xvfb-run python eval_3dfront.py xxx`, but I am not sure.
Good luck!

**Comment by Aoihigashi** [comment]
> Hi,
> Thanks for trying and bearing with me. I never tried to run on a headless server actually, so maybe some rendering code wouldn't work properly and need some adjustments. The problematic line I saw you were trying is top-down image rendering. If you don't really need it, just need to turn `store_img` as `False` [here](https://github.com/ymxlzgy/commonscenes/blob/1665ffb81a32d7337d9c0caad1262917b37c39e0/scripts/eval_3dfront.py#L575), or you need to adjust pyrender settings for the headless rendering. From what I googled, you can try to use `xvfb-run` by `xvfb-run python eval_3dfront.py xxx`, but I am not sure.
> Good luck!

Thank you for your response. I will try the methods you mentioned.

**Comment by weiyao1996** [comment]
EGL works for me. Please refer to https://pyrender.readthedocs.io/en/latest/examples/offscreen.html
