### ISSUE TITLE
Issue with Overlapping Objects and Incorrect Bounding Box Sizes in 3D-FRONT Dataset Preprocessing with ATISS

### ISSUE THREAD

**Issue by atcelen** [ymxlzgy/commonscenes#4]
Hello,

I appreciate the excellent work on the project. I have been working with the new version of the 3D-FRONT dataset and encountered an issue during the preprocessing phase using the ATISS repository.

**Problem:**
There seems to be a challenge with overlapping objects and discrepancies in bounding box sizes. As an illustration, you can refer to the example below, where some object sizes appear to be inconsistent.

**Example:**
You can find two 2d visualization of both 3D-Front versions below.

**Question:**
Have you come across similar issues, and do you have any recommendations or solutions for addressing this problem during the preprocessing of the 3D-FRONT dataset with ATISS?

Thank you for your assistance!

The example:

**USING THE OLD VERSION OF 3D-FRONT**

![TDFront_ce3aa96b-a6f4-455d-8a83-2a61253c6fec_LivingDiningRoom-2432_2 jpg](https://github.com/ymxlzgy/commonscenes/assets/50236904/038c5776-0730-4b48-b4a7-95445c8c05fb)

**USING THE NEW VERSION OF 3D-FRONT (CLASS LABELS CAN BE DISREGARDED)**
![rel](https://github.com/ymxlzgy/commonscenes/assets/50236904/8ad00ca0-0dfd-4451-b2db-9bc3d7af0e8f)

**Comment by ymxlzgy** [comment]
Hi, I appreciate that you pointed out this problem. I was never able to download the old version of 3D-FRONT, though. Indeed, I have seen many penetration cases in the new 3D-FRONT preprocessed by ATISS. I also consulted other researchers working on the new 3D-FRONT previously. It turned out that it seemed to be the inherent problem with the dataset, so I just left it alone without solving it.

**Comment by atcelen** [comment]
It's intriguing that the recently released dataset contains these kind of errors! Additionally, you can locate the download link for the previous version of the dataset below:

- https://tianchi-media.oss-accelerate.aliyuncs.com/65347_3D-future/3D-FUTURE-model.zip
- https://tianchi-media.oss-accelerate.aliyuncs.com/65347_3D-future/3D-FRONT.zip
