### ISSUE TITLE
about scene graph visualization 

### ISSUE THREAD

**Issue by Aoihigashi** [ymxlzgy/commonscenes#6]
Hi,
Thanks for sharing your work.
I was wondering is there any code or is it manually drawn to convert the scene graph from a JSON file into an intuitively visualized scene graph as shown in the results figure in the paper? Thank you very much for your time and answer.

**Comment by ymxlzgy** [comment]
Hi,
Thanks for asking. It is actually an interesting fact. We use the script provided here to label and visualize the graph: [see the last line](https://sites.google.com/view/commonscenes/dataset#:~:text=The%20dataset%20is%20released%20under%20MIT%20license.%20Our%20automatic%20labeling%20setup%20can%20be%20downloaded%20here%20for%20reference%20and%20potential%20adjustment.) Download `threedfront_sg.py`, you can see there is `from graphviz import Digraph` and a function `visualize_scene_graph`. You don't need to recreate the scene graph, and I suppose you can just use this function to have the graph with proper input. But to install `graphviz`, you may need a python 3.7 environment (I didn't succeed under 3.8). Then, you will have some visualization as shown [here](https://github.com/ymxlzgy/commonscenes/tree/main/dataset/tmp). 

To obtain the graph shown in the paper, I recommend draw.io with which you can draw edges and nodes according to the graph visualization. We only picked and drew the important edges in the paper,  as the original visualization is too complicated to be shown....

**Comment by Aoihigashi** [comment]
> Hi, Thanks for asking. It is actually an interesting fact. We use the script provided here to label and visualize the graph: [see the last line](https://sites.google.com/view/commonscenes/dataset#:~:text=The%20dataset%20is%20released%20under%20MIT%20license.%20Our%20automatic%20labeling%20setup%20can%20be%20downloaded%20here%20for%20reference%20and%20potential%20adjustment.) Download `threedfront_sg.py`, you can see there is `from graphviz import Digraph` and a function `visualize_scene_graph`. You don't need to recreate the scene graph, and I suppose you can just use this function to have the graph with proper input. But to install `graphviz`, you may need a python 3.7 environment (I didn't succeed under 3.8). Then, you will have some visualization as shown [here](https://github.com/ymxlzgy/commonscenes/tree/main/dataset/tmp).
> 
> To obtain the graph shown in the paper, I recommend draw.io with which you can draw edges and nodes according to the graph visualization. We only picked and drew the important edges in the paper, as the original visualization is too complicated to be shown....

Thanks for your response. Does that mean I only need to provide the visualize_scene_graph function with the appropriate input, rather than running the entire threedfront_sg.py file?

**Comment by ymxlzgy** [comment]
> > Hi, Thanks for asking. It is actually an interesting fact. We use the script provided here to label and visualize the graph: [see the last line](https://sites.google.com/view/commonscenes/dataset#:~:text=The%20dataset%20is%20released%20under%20MIT%20license.%20Our%20automatic%20labeling%20setup%20can%20be%20downloaded%20here%20for%20reference%20and%20potential%20adjustment.) Download `threedfront_sg.py`, you can see there is `from graphviz import Digraph` and a function `visualize_scene_graph`. You don't need to recreate the scene graph, and I suppose you can just use this function to have the graph with proper input. But to install `graphviz`, you may need a python 3.7 environment (I didn't succeed under 3.8). Then, you will have some visualization as shown [here](https://github.com/ymxlzgy/commonscenes/tree/main/dataset/tmp).
> > To obtain the graph shown in the paper, I recommend draw.io with which you can draw edges and nodes according to the graph visualization. We only picked and drew the important edges in the paper, as the original visualization is too complicated to be shown....
> 
> Thanks for your response. Does that mean I only need to provide the visualize_scene_graph function with the appropriate input, rather than running the entire threedfront_sg.py file?

True. Good luck! I would close this for now. Feel free to reopen it.

**Comment by Aoihigashi** [comment]
> > > Hi, Thanks for asking. It is actually an interesting fact. We use the script provided here to label and visualize the graph: [see the last line](https://sites.google.com/view/commonscenes/dataset#:~:text=The%20dataset%20is%20released%20under%20MIT%20license.%20Our%20automatic%20labeling%20setup%20can%20be%20downloaded%20here%20for%20reference%20and%20potential%20adjustment.) Download `threedfront_sg.py`, you can see there is `from graphviz import Digraph` and a function `visualize_scene_graph`. You don't need to recreate the scene graph, and I suppose you can just use this function to have the graph with proper input. But to install `graphviz`, you may need a python 3.7 environment (I didn't succeed under 3.8). Then, you will have some visualization as shown [here](https://github.com/ymxlzgy/commonscenes/tree/main/dataset/tmp).
> > > To obtain the graph shown in the paper, I recommend draw.io with which you can draw edges and nodes according to the graph visualization. We only picked and drew the important edges in the paper, as the original visualization is too complicated to be shown....
> > 
> > 
> > Thanks for your response. Does that mean I only need to provide the visualize_scene_graph function with the appropriate input, rather than running the entire threedfront_sg.py file?
> 
> True. Good luck! I would close this for now. Feel free to reopen it.

Hello, I'm sorry to bother you again. I noticed that in threedfront_sg.py there is a csv file path '/media/ymxlzgy/Data/Dataset/3D-FRONT/object_ids.csv'. Where can I find this file? I only found 'bedroom_threed_front_splits.csv' and other room type, but I didn't see any information about color in these files. Thank you very much for your help.

**Comment by SceneLinker** [comment]
> > > > Hi, Thanks for asking. It is actually an interesting fact. We use the script provided here to label and visualize the graph: [see the last line](https://sites.google.com/view/commonscenes/dataset#:~:text=The%20dataset%20is%20released%20under%20MIT%20license.%20Our%20automatic%20labeling%20setup%20can%20be%20downloaded%20here%20for%20reference%20and%20potential%20adjustment.) Download `threedfront_sg.py`, you can see there is `from graphviz import Digraph` and a function `visualize_scene_graph`. You don't need to recreate the scene graph, and I suppose you can just use this function to have the graph with proper input. But to install `graphviz`, you may need a python 3.7 environment (I didn't succeed under 3.8). Then, you will have some visualization as shown [here](https://github.com/ymxlzgy/commonscenes/tree/main/dataset/tmp).
> > > > To obtain the graph shown in the paper, I recommend draw.io with which you can draw edges and nodes according to the graph visualization. We only picked and drew the important edges in the paper, as the original visualization is too complicated to be shown....
> > > 
> > > 
> > > Thanks for your response. Does that mean I only need to provide the visualize_scene_graph function with the appropriate input, rather than running the entire threedfront_sg.py file?
> > 
> > 
> > True. Good luck! I would close this for now. Feel free to reopen it.
> 
> Hello, I'm sorry to bother you again. I noticed that in threedfront_sg.py there is a csv file path '/media/ymxlzgy/Data/Dataset/3D-FRONT/object_ids.csv'. Where can I find this file? I only found 'bedroom_threed_front_splits.csv' and other room type, but I didn't see any information about color in these files. Thank you very much for your help.

Hello, I am struggling with trying to visualise the scene graph. 
Do you know where you got the 'object_ids.csv' file from?
