### ISSUE TITLE
The training instructions of VQ-VAE codec 

### ISSUE THREAD

**Issue by Qi-Chuan** [ymxlzgy/commonscenes#7]
Hi,
Thanks for sharing your work. I noticed that the VQ-VAE model is provided with pre-trained weights. But if I want to train the whole framework from scratch, could you tell me how to train the 3D shape VQ-VAE codecs？

**Comment by ymxlzgy** [comment]
Hi, we follow this section to train the VQ-VAE: [see here.](https://github.com/yccyenchicheng/SDFusion#training) Just write a data loader reading 3D-FUTURE-models.

**Comment by Qi-Chuan** [comment]
> Hi, we follow this section to train the VQ-VAE: [see here.](https://github.com/yccyenchicheng/SDFusion#training) Just write a data loader reading 3D-FUTURE-models.

Thanks for your reply! Could you please share me the codes of the data loader part for study and reference? My email is 920892753@qq.com. Thanks a lot!

**Comment by ymxlzgy** [comment]
> > Hi, we follow this section to train the VQ-VAE: [see here.](https://github.com/yccyenchicheng/SDFusion#training) Just write a data loader reading 3D-FUTURE-models.
> 
> Thanks for your reply! Could you please share me the codes of the data loader part for study and reference? My email is [920892753@qq.com](mailto:920892753@qq.com). Thanks a lot!

My colleague Evin @evinpinar did the VQ-VAE part. Please feel free to email her for the code query. Thanks!
