### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by yangzhifeio** [ymxlzgy/commonscenes#8]
Thanks for your great work!
 def select_sdfs(self, dec_objs_to_scene, dec_objs, dec_objs_grained, dec_sdfs, uc_rel_feat, c_rel_feat, random=False):
 I would like to ask you what this function does
 thanks!

**Comment by ymxlzgy** [comment]
This can be referred in the supplementary material. This samples objects from all scenes in a batch to train the Diffusion model, aiming at make the training work on limited GPU resources.

**Comment by ymxlzgy** [comment]
If one has more issues, feel free to re-open this issue or restart a new one.
